### ISSUE TITLE
ScatterCtrl.usc(73,46): number expected for '-', encountered "55"

### ISSUE THREAD

**Issue by erusyd** [anboto/Scatter#6]
I opened ScatterCtrl_Demo in TheIDE, layout file has this warning:
![image](https://github.com/anboto/Scatter/assets/1529102/c5714c7e-bd55-4c43-a818-a347bf559265)

**Comment by izabala123** [comment]
Hi [erusyd](https://github.com/erusyd)

Yes you are right. Fix is commited, please check, 
Thank you!

Iñaki

**Comment by erusyd** [comment]
Nice.
![image](https://github.com/anboto/Scatter/assets/1529102/7fc779ee-6619-4364-8a55-d4765d11e4e3)
