### ISSUE TITLE
SetMajorUnitsNum removed

### ISSUE THREAD

**Issue by Maginor** [anboto/Scatter#7]
This function was removed from ScatterDraw.cpp, but not from ScatterDraw.h .

Also, I was using it quite a bit. Could it be put back in?

**Comment by Maginor** [comment]
If you don't want to add it back in, just let me know. There are workarounds.

**Comment by izabala123** [comment]
Hi Maginor

I have re-added that function. However, after last internal changes (AdjustMajorUnit*() and others), ScatterDraw sets by itself the major units to have the minimum number of significant digits (see [this](https://www.ultimatepp.org/forums/index.php?t=msg&th=12142&start=0&) post). This way, I have had to include a simple version of SetMajorUnitsNum(). Please confirm me that this is right for you.

Best regards
Iñaki

**Comment by Maginor** [comment]
Hi,
The new adjustments are useful since I had written my own function to do this before.

The behaviour for SetMajorUnitsNum is not identical to before in a case where it matters, and where I don't want to adjust the grid lines based on the significant digits.
As I said, I could maybe fix it using SetGridLinesX / SetGridLinesY, but it depends on whether or not you want to support the old SetMajorUnitsNum functionality.

I have many small plots where I want the axes either to not have a grid unit or have one at the exact beginning and end of the axis.

Code:
```
plot.SetXYMin(min_x, min_y).SetRange(max_x-min_x, max_y-min_y)
//plot.SetMinUnits(0.0, 0.0).SetMajorUnits(max_x-min_x, max_y-min_y);
plot.SetMajorUnitsNum(major_units_num_x, major_units_num_y);
```
where major_units_num_x and major_units_num_y are either 0 or 1.

This is what I had before:
![image](https://github.com/anboto/Scatter/assets/28389991/3247bd9d-fb7f-490f-8893-fcb461d5296f)

This is what I get now:
![image](https://github.com/anboto/Scatter/assets/28389991/b2428069-fe7a-4e68-a951-b50722aefa49)

Best regards,
Magnus

**Comment by izabala123** [comment]
Hi Magnus

Thank you. I have changed SetMinUnits() so that it does not try to reset the grid. To work properly, please put SetMinUnits() just at the end of all functions.

To avoid having vertical grid at all you can set these:
`SetDrawXReticle(false).SetDrawXReticleNumbers(false).ShowVGrid(false)`

Best regards
Iñaki

**Comment by Maginor** [comment]
Edit: it is fixed now. I forgot I did another update on the plot later.

**Comment by Maginor** [comment]
It seems to work correctly now!
