### ISSUE TITLE
Bug if last or all values in a line series plot is Null

### ISSUE THREAD

**Issue by Maginor** [anboto/Scatter#8]
Hi,
If the n last values or all the values in a series are Null, the plot of the series is unpredictable.
Sometimes it plots an arbitrary line, or one that goes to +infinity.
It should just not plot a line for the empty values.

**Comment by izabala123** [comment]
Hi Maginor

Thank you for reporting. I am sure you have found something but I am unable to reproduce it.
I have added two Null at the end of NullDataDemo()

![image](https://github.com/anboto/Scatter/assets/38589221/20ce5e11-aae4-41ee-8dc3-926cf550a3a7)

And the plot is this:

![Scatter null data](https://github.com/anboto/Scatter/assets/38589221/12744b50-448d-409b-ade2-fb1b241762f2)

It does not look bad. Did you expect anything different?

Best regards
Iñaki

**Comment by Maginor** [comment]
Thank you for looking at it.

It is unpredictable behaviour, so some times it happens and some times the behaviour is correct.

**I notice now that it only happens when I have SetFastViewX(true) on.**

What I have is is several series that are added using
AddSeries(double *yData, int numData, double x0 = 0, double deltaX = 1)

The yData is initially filled with
std::numeric_limits<double>::quiet_NaN()

Then all the series are gradually filled in over time (all of them up to the same index).
You can see in the plot below that in some of the series, they end with a line to positive infinity. This comes randomly on and off as I update the series. This bug was introduced between now and march this year.

The other bug that I mentioned, that the plot is unpredictable when all the Y values are NaN has been there for longer, and always seems to happen.

![image](https://github.com/anboto/Scatter/assets/28389991/8a10172a-4ae5-4c20-a005-3a04819b0003)

**Comment by izabala123** [comment]
Hi Magnus

Thank you for your patience. I am sorry but I cannot reproduce your error, ScatterDraw_demo_cl NullDataDemo() includes as well SetFastViewX(true), various Null, and the behaviour is as I reported in previous post.

Anyway, to support better quiet_NaN(), I have replaced the IsNull() with IsNum(), that checks stronger the validity of the value. Please check if it works.

If it doesn't, in order to find out what the cause of the problem is, I wanted to ask you to take the ScatterDraw_demo_cl example, modify it to cause the problems you are experiencing, and send me the source code, so that I can reproduce it on my computer, and find and solve the cause.

Best regards
Iñaki

**Comment by Maginor** [comment]
The below code produces the following image for me. You can see from the code that the line should not be able to go above 1 on the Y axis.
Interestingly, the bug only happens when the NaN tail is very large, it doesn't happen when I increase the length of the non-nan head to e.g. 1000.
Note also what happens if the vec is entirely made up of NaNs.

![image](https://github.com/anboto/Scatter/assets/28389991/5f7db956-f924-466b-a934-2c06aeb4baa9)


```
void NullDataDemo(String fileName) {
	ScatterDraw scatter;

	UppLog() << "\nPreparing Null data scatter";

	scatter.SetSequentialXAll().SetFastViewX();

	std::mt19937 gen;
    std::uniform_real_distribution<double> distr(0, 1);
	
	constexpr int num = 5000;

	std::vector<double> vec(num);
	for(int i = 0; i < vec.size(); ++i) {
		if(i < 300)
			vec[i] = distr(gen);
		else
			vec[i] = std::numeric_limits<double>::quiet_NaN();
	}
	scatter.AddSeries(vec.data(), vec.size(), 0, 1).NoMark().Stroke(1.5, Color(0, 0, 0)).Dash("");

	scatter.SetSize(Size(250, 200)).ShowLegend(false);;
	scatter.SetXYMin(0, -0.5).SetRange(num, 2);
	
	fileName = fileName + " null data.png";
	PNGEncoder().SaveFile(fileName, scatter.GetImage());	
	
	UppLog() << "\nSaved '" << fileName << "'";
}
```

**Comment by izabala123** [comment]
Hi Magnus

Thank you!. Without your example I would not have found the problem, as it is really elusive. 
Please try the correction. Thank you very much for your patience.

Iñaki

**Comment by Maginor** [comment]
It seems correct now!
Thank you for always fixing problems quickly and being patient with my obscure use cases :)

**Comment by izabala123** [comment]
Hi Magnus

Sometimes the difference between a "decent" library and a "good" one is that the decent one "usually" works well, and the good one "just" works well. And the difference is in the details. Thank you very much for reporting "obscure cases". You really help me a lot.

Best regards
Iñaki
