### ISSUE TITLE
Problems with series Data .csv export

### ISSUE THREAD

**Issue by Maginor** [anboto/Scatter#9]
``The Data display is almost correct with the right formatting for the X axis (though the unit of the series appears twice in the table header, but not on the tab)
![image](https://github.com/anboto/Scatter/assets/28389991/02590345-e5de-4066-bb4e-0744f2fbb22f)

However, if I export as .csv I get this, that is the x axis is exported as numbers, not formatted:
```
 ;Reach flow ["Coull"][m³ s⁻¹] [m³ s⁻¹]
725760000;0.50998501615494
725846400;0.522514237107716
725932800;0.514004883746867
726019200;0.532915190348337
726105600;0.505512982967228
726192000;0.495297083974595
726278400;0.615529682779027
726364800;1.18930706999156
726451200;0.923183048939487
726537600;0.939084899938687
726624000;0.885312298562855
726710400;0.835864069451411
726796800;0.794849200410477
```

**Comment by izabala123** [comment]
Hi Maginor

Yes you are right. I hope it is fixed now.
About the units in the header, now it is fixed, although I suppose that you have done anything like this
`scatter.Legend("2005 [ºC]").Units("ºC");`
, repeating the units in the legend and the units.

Best regards
Iñaki

**Comment by Maginor** [comment]
Hi, there was some reason why I had to repeat the the unit in the title and the legend:
I think it is because if you add something else in a [] bracket in the legend it assumes that is the unit, and that is not always correct in my case since I also use [] to denote indexing, like "Reach water flow [Outlet][m3/s]" (so I have to add the unit after that in the legend so that it doesn't assume [Outlet] is the unit). 

It now exports the dates correctly, but in the "All" view, it no longer puts the name of each series in the array header:
![image](https://github.com/anboto/Scatter/assets/28389991/2155e083-38fd-4308-8b49-b1cacc7681f1)
(this is not critical since they are the same as in the tabs)

**Comment by izabala123** [comment]
Hi Magnus

I don't know how to reproduce the problem.
Running ScatterCtrl_demo I get this:

![image](https://github.com/anboto/Scatter/assets/38589221/b3add3db-0dc7-46e2-b707-1369eadfe982)

Best regards
Iñaki

**Comment by izabala123** [comment]
Ups, there was an error. Now hopefully fixed:
![image](https://github.com/anboto/Scatter/assets/38589221/74d9fd9e-8b4c-4ae2-8915-4d4d03b9a391)

**Comment by Maginor** [comment]
It is now correct.

**Comment by izabala123** [comment]
Hi Magnus

Thank you for reporting and for testing!

Iñaki
